### ISSUE TITLE
[Error] Object reference not set to an instance of an object in Xamarin.iOS

### ISSUE THREAD

**Issue by JaeWLee** [CrossGeeks/GoogleClientPlugin#5] opened 2018-07-17 07:33 UTC
I had above error in "GoogleClientManager.Initialize();"

At first, I can't build with some error
and I add **"--registrar:static"** in 'iOS Build' in Project options

At second, I can't build with error, too
> /Users/cheonmyeong-gi/Desktop/HopsProject/HopsMobile/HopsMobile.iOS/clang: Error: no such file or directory: '/Users/cheonmyeong-gi/Desktop/HopsProject/HopsMobile/HopsMobile.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone8.4-11.4/mtouch-cache/GoogleSignIn' (HopsMobile.iOS)
so, I add package **'Xamarin.Google.iOS.SignIn'**
and fixed error

But, now had another error
<img width="1141" alt="screen shot 2018-07-17 at 4 25 27 pm" src="https://user-images.githubusercontent.com/35772429/42802848-0dcb0bb4-89df-11e8-96f0-4bec3ee23bd9.png">

I add GoogleService-info.plist

How I solve this?

**Comment by Pujolsluis** [comment] 2018-07-17 13:23
Hey @JaeWLee ,

Make sure you have completed the [Google Firebase Console Setup](https://github.com/CrossGeeks/GoogleClientPlugin/blob/master/GoogleClient/docs/GoogleFirebaseConsoleSetup.md) iOS section, specifically steps 3 and 4 are very important and may be the cause of this issue. 

Also if you wish to deploy your app on the iOS simulator or your physical device remember you must set up a provisioning profile so the app launches correctly.

**Comment by JaeWLee** [comment] 2018-07-18 13:59
@Pujolsluis 
I found solution!!

We have to set **GoogleService-info.plist**'s '**Build Action**' to '**BundleResource**'

**Comment by Pujolsluis** [comment] 2018-07-18 17:14
Great Job! @JaeWLee hehe. yeah, I will make the note about the BundleAction on Step 2 of the guide more noticeable, I will proceed to close this issue since it's solved.

Best of luck on your project. 👍

**Closed by Pujolsluis** 2018-07-18 17:14 UTC
